using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO.Compression;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.OutputVisitor;
using ICSharpCode.Decompiler.CSharp.ProjectDecompiler;
using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.CSharp.Transforms;
using ICSharpCode.Decompiler.DebugInfo;
using ICSharpCode.Decompiler.IL;
using ICSharpCode.Decompiler.Metadata;
using ICSharpCode.Decompiler.TypeSystem;
using ICSharpCode.Decompiler.Util;
using SequencePoint = ICSharpCode.Decompiler.DebugInfo.SequencePoint;

namespace SharpDbg.Infrastructure.Debugger.Decompilation;

public class PortablePdbWriter2
{
	const string decompilerVersion = DecompilerVersionInfo.Version;

	/// <summary>Suppresses the "generated by ICSharpCode.Decompiler" header comment in each source file.</summary>
	public bool NoLogo { get; set; }

	/// <summary>
	/// The PDB id (GUID + stamp) to stamp into the generated PDB. When <c>null</c> (the default) the
	/// id is taken from the assembly's CodeView debug-directory entry so the PDB matches the PE.
	/// </summary>
	public BlobContentId? PdbId { get; set; }

	/// <summary>Optional per-file progress reporter.</summary>
	public IProgress<DecompilationProgress> Progress { get; set; }

	/// <summary>The title surfaced through <see cref="Progress"/>.</summary>
	public string CurrentProgressTitle { get; set; } = "Generating portable PDB...";

	/// <summary>
	/// When <c>true</c> (the default) each decompiled source file is embedded into the PDB. Set to
	/// <c>false</c> when the source is already written to disk (e.g. alongside a project export) so
	/// the PDB stays small and references the on-disk files instead. The per-document checksum/hash
	/// is written either way.
	/// </summary>
	public bool EmbedSourceFiles { get; set; } = true;

	public static bool HasCodeViewDebugDirectoryEntry(PEFile file)
	{
		return file != null && file.Reader.ReadDebugDirectory().Any(entry => entry.Type == DebugDirectoryEntryType.CodeView);
	}

	private static bool IncludeTypeWhenGeneratingPdb(PEFile module, TypeDefinitionHandle type, DecompilerSettings settings)
	{
		var metadata = module.Metadata;
		var typeDef = metadata.GetTypeDefinition(type);
		string name = metadata.GetString(typeDef.Name);
		string ns = metadata.GetString(typeDef.Namespace);
		if (name == "<Module>" || CSharpDecompiler.MemberIsHidden(module, type, settings))
			return false;
		if (ns == "XamlGeneratedNamespace" && name == "GeneratedInternalTypeHelper")
			return false;
		if (!typeDef.IsNested && RemoveEmbeddedAttributes.attributeNames.Contains(ns + "." + name))
			return false;
		return true;
	}

	private static CSharpDecompiler NewDecompiler(DecompilerTypeSystem decompilerTypeSystem, DecompilerSettings decompilerSettings)
	{
		var decompiler = new CSharpDecompiler(decompilerTypeSystem, decompilerSettings)
		{
			AstTransforms = {
				new EscapeInvalidIdentifiers(),
				new RemoveCLSCompliantAttribute()
				// most other transforms are already present by default
			}
		};
		return decompiler;
	}

	public Dictionary<string, string> WritePdb(
		PEFile file,
		DecompilerTypeSystem decompilerTypeSystem,
		DecompilerSettings settings,
		Stream targetStream,
		int maxDegreeOfParallelism = -1,
		CancellationToken cancellationToken = default)
	{
		BlobContentId? pdbId = PdbId;
		MetadataBuilder metadata = new MetadataBuilder();
		MetadataReader reader = file.Metadata;
		var entrypointHandle = MetadataTokens.MethodDefinitionHandle(file.Reader.PEHeaders.CorHeader.EntryPointTokenOrRelativeVirtualAddress);

		var sequencePointBlobs = new Dictionary<MethodDefinitionHandle, (DocumentHandle Document, BlobHandle SequencePoints)>();
		var localScopes = new List<(MethodDefinitionHandle Method, ImportScopeInfo Import, int Offset, int Length, HashSet<ILVariable> Locals)>();
		var stateMachineMethods = new List<(MethodDefinitionHandle MoveNextMethod, MethodDefinitionHandle KickoffMethod)>();
		var customDebugInfo = new List<(EntityHandle Parent, GuidHandle Guid, BlobHandle Blob)>();
		var customMethodDebugInfo = new List<(MethodDefinitionHandle Parent, GuidHandle Guid, BlobHandle Blob)>();
		var globalImportScope = metadata.AddImportScope(default, default);
		var collectedSourceFiles = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

		var assemblyName = reader.GetString(reader.GetAssemblyDefinition().Name);
		var mvid = reader.GetGuid(reader.GetModuleDefinition().Mvid);
		var sourceFilePrefix = Path.Combine("decompiled", assemblyName, mvid.ToString());

		string BuildFileNameFromTypeName(TypeDefinitionHandle handle)
		{
			var typeName = handle.GetFullTypeName(reader).TopLevelTypeName;
			string ns = settings.UseNestedDirectoriesForNamespaces
				? WholeProjectDecompiler.CleanUpPath(typeName.Namespace)
				: WholeProjectDecompiler.CleanUpDirectoryName(typeName.Namespace);
			return Path.Combine(sourceFilePrefix, ns, WholeProjectDecompiler.CleanUpFileName(typeName.Name, ".cs"));
		}

		var sourceFiles = reader.GetTopLevelTypeDefinitions().Where(t => IncludeTypeWhenGeneratingPdb(file, t, settings)).GroupBy(BuildFileNameFromTypeName).ToList();
		DecompilationProgress currentProgress = new() {
			TotalUnits = sourceFiles.Count,
			UnitsCompleted = 0,
			Title = CurrentProgressTitle
		};

		var perFileResults = new ConcurrentBag<PerFileResult>();

		Parallel.ForEach(
			Partitioner.Create(sourceFiles, loadBalance: true),
			new ParallelOptions
			{
				MaxDegreeOfParallelism = maxDegreeOfParallelism <= 0 ? Environment.ProcessorCount : maxDegreeOfParallelism,
				CancellationToken = cancellationToken
			},
			sourceFile =>
			{
				// Create a per-task decompiler that shares the same type system but is otherwise independent.
				var taskDecompiler = NewDecompiler(decompilerTypeSystem, settings);
				taskDecompiler.CancellationToken = cancellationToken;

				// Generate syntax tree
				var syntaxTree = taskDecompiler.DecompileTypes(sourceFile);

				if (Progress != null)
				{
					Interlocked.Increment(ref currentProgress.UnitsCompleted);
					Progress.Report(currentProgress);
				}

				if (!syntaxTree.HasChildren)
					return;

				// Generate source and checksum
				if (!NoLogo)
					syntaxTree.PrependLeadingTrivia(new Comment(" PDB and source generated by ICSharpCode.Decompiler " + decompilerVersion));
				var sourceText = SyntaxTreeToString(syntaxTree, settings);

				// Generate sequence points for the syntax tree
				var sequencePoints = taskDecompiler.CreateSequencePoints(syntaxTree);

				// Generate other debug information (all per-task, no shared state)
				var debugInfoGen = new DebugInfoGenerator(taskDecompiler.TypeSystem);
				syntaxTree.AcceptVisitor(debugInfoGen);

				perFileResults.Add(new PerFileResult(sourceFile.Key, sourceText, syntaxTree, sequencePoints, debugInfoGen));
			});

		foreach (var result in perFileResults)
		{
			// The document hash is always required; the source blob is only embedded when asked.
			var sourceCheckSum = ComputeSourceChecksum(result.SourceText);
			var name = metadata.GetOrAddDocumentName(result.Key);

			// Create Document(Handle)
			var document = metadata.AddDocument(name,
				hashAlgorithm: metadata.GetOrAddGuid(KnownGuids.HashAlgorithmSHA256),
				hash: metadata.GetOrAddBlob(sourceCheckSum),
				language: metadata.GetOrAddGuid(KnownGuids.CSharpLanguageGuid));

			// Add embedded source to the PDB
			if (EmbedSourceFiles)
			{
				customDebugInfo.Add((document,
					metadata.GetOrAddGuid(KnownGuids.EmbeddedSource),
					WriteSourceToBlob(metadata, result.SourceText)));
			}

			result.DebugInfoGen.GenerateImportScopes(metadata, globalImportScope);

			localScopes.AddRange(result.DebugInfoGen.LocalScopes);

			collectedSourceFiles[result.Key] = result.SourceText;

			foreach (var function in result.DebugInfoGen.Functions)
			{
				var method = function.MoveNextMethod ?? function.Method ?? throw new InvalidOperationException("Function does not have a method associated with it");
				var methodHandle = (MethodDefinitionHandle)method.MetadataToken;
				result.SequencePoints.TryGetValue(function, out var points);
				ProcessMethod(methodHandle, document, points, result.SyntaxTree);
				if (function.MoveNextMethod != null)
				{
					stateMachineMethods.Add((
						(MethodDefinitionHandle)function.MoveNextMethod.MetadataToken,
						(MethodDefinitionHandle)function.Method.MetadataToken
					));
					customDebugInfo.Add((
						function.MoveNextMethod.MetadataToken,
						metadata.GetOrAddGuid(KnownGuids.StateMachineHoistedLocalScopes),
						metadata.GetOrAddBlob(BuildStateMachineHoistedLocalScopes(function))
					));
				}
				// Runtime-async methods (.NET 11) are IsAsync from their signature but carry no
				// state machine, so AsyncAwaitDecompiler never populates AsyncDebugInfo and its
				// Awaits stays an uninitialized ImmutableArray. They have no yield/resume offsets
				// to record, so omit stepping information entirely - matching the C# compiler,
				// which emits none either - rather than build a blob from the default struct.
				if (function.IsAsync && !function.AsyncDebugInfo.Awaits.IsDefault)
				{
					customMethodDebugInfo.Add((methodHandle,
						metadata.GetOrAddGuid(KnownGuids.MethodSteppingInformation),
						metadata.GetOrAddBlob(function.AsyncDebugInfo.BuildBlob(methodHandle))));
				}
			}

			// Sequence points are keyed by the ILFunction resolved through the IL instruction
			// tree, which still resolves for member initializers that were lifted out of a
			// constructor the decompiler omits from the output (an implicit default constructor,
			// an implicit static constructor, or a primary constructor). DebugInfoGenerator only
			// discovers functions through their declaration syntax, so those constructors are not
			// in its set; emit their sequence points here so the lifted initializers stay
			// breakpointable.
			var emittedFunctions = new HashSet<ILFunction>(result.DebugInfoGen.Functions);
			foreach (var (function, points) in result.SequencePoints)
			{
				if (!emittedFunctions.Add(function))
					continue;
				var method = function.MoveNextMethod ?? function.Method;
				if (method == null || method.MetadataToken.IsNil)
					continue;
				ProcessMethod((MethodDefinitionHandle)method.MetadataToken, document, points, result.SyntaxTree);
			}
		}

		foreach (var method in reader.MethodDefinitions)
		{
			var md = reader.GetMethodDefinition(method);

			if (sequencePointBlobs.TryGetValue(method, out var info))
			{
				metadata.AddMethodDebugInformation(info.Document, info.SequencePoints);
			}
			else
			{
				metadata.AddMethodDebugInformation(default, default);
			}
		}

		localScopes.Sort((x, y) => {
			if (x.Method != y.Method)
			{
				return MetadataTokens.GetRowNumber(x.Method) - MetadataTokens.GetRowNumber(y.Method);
			}
			if (x.Offset != y.Offset)
			{
				return x.Offset - y.Offset;
			}
			return y.Length - x.Length;
		});
		foreach (var localScope in localScopes)
		{
			int nextRow = metadata.GetRowCount(TableIndex.LocalVariable) + 1;
			var firstLocalVariable = MetadataTokens.LocalVariableHandle(nextRow);

			foreach (var local in localScope.Locals.OrderBy(l => l.Index))
			{
				var localVarName = local.Name != null ? metadata.GetOrAddString(local.Name) : default;
				metadata.AddLocalVariable(LocalVariableAttributes.None, local.Index.Value, localVarName);
			}

			metadata.AddLocalScope(localScope.Method, localScope.Import.Handle, firstLocalVariable,
				default, localScope.Offset, localScope.Length);
		}

		stateMachineMethods.SortBy(row => MetadataTokens.GetRowNumber(row.MoveNextMethod));
		foreach (var row in stateMachineMethods)
		{
			metadata.AddStateMachineMethod(row.MoveNextMethod, row.KickoffMethod);
		}
		customMethodDebugInfo.SortBy(row => MetadataTokens.GetRowNumber(row.Parent));
		foreach (var row in customMethodDebugInfo)
		{
			metadata.AddCustomDebugInformation(row.Parent, row.Guid, row.Blob);
		}
		customDebugInfo.SortBy(row => MetadataTokens.GetRowNumber(row.Parent));
		foreach (var row in customDebugInfo)
		{
			metadata.AddCustomDebugInformation(row.Parent, row.Guid, row.Blob);
		}

		if (pdbId == null)
		{
			var debugDir = file.Reader.ReadDebugDirectory().Cast<DebugDirectoryEntry?>().LastOrDefault(dir => dir!.Value.Type == DebugDirectoryEntryType.CodeView);
			if (debugDir is not null)
			{
				var portable = file.Reader.ReadCodeViewDebugDirectoryData(debugDir.Value);
				Debug.Assert(!portable.Path.EndsWith(".ni.pdb"));
				pdbId = new BlobContentId(portable.Guid, debugDir.Value.Stamp);
			}
			else throw new InvalidOperationException("Dll did not contain a CodeView entry, unable to determine PdbId. Are you trying to decompile a Publicized assembly?");
		}

		PortablePdbBuilder serializer = new PortablePdbBuilder(metadata, GetRowCounts(reader), entrypointHandle, blobs => pdbId.Value);
		BlobBuilder blobBuilder = new BlobBuilder();
		serializer.Serialize(blobBuilder);
		blobBuilder.WriteContentTo(targetStream);

		return collectedSourceFiles;

		void ProcessMethod(MethodDefinitionHandle method, DocumentHandle document,
			List<SequencePoint> sequencePoints, SyntaxTree syntaxTree)
		{
			var methodDef = reader.GetMethodDefinition(method);
			int localSignatureRowId;
			MethodBodyBlock methodBody;
			if (methodDef.RelativeVirtualAddress != 0)
			{
				methodBody = file.Reader.GetMethodBody(methodDef.RelativeVirtualAddress);
				localSignatureRowId = methodBody.LocalSignature.IsNil ? 0 : MetadataTokens.GetRowNumber(methodBody.LocalSignature);
			}
			else
			{
				methodBody = null;
				localSignatureRowId = 0;
			}

			// Check if sequence points were already processed - ILFunction gets defined in C# twice:
			// This may happen if a compiler-generated function gets transformed into a lambda expression,
			// but its method definition is not removed from the syntax tree.
			if (!sequencePointBlobs.ContainsKey(method))
			{
				if (sequencePoints?.Count > 0)
					sequencePointBlobs.Add(method, (document, EncodeSequencePoints(metadata, localSignatureRowId, sequencePoints)));
				else
					sequencePointBlobs.Add(method, (default, default));
			}
			else
			{
				Debug.Assert(false, "Duplicate sequence point definition detected: " + MetadataTokens.GetToken(method).ToString("X8"));
			}
		}
	}

	static BlobBuilder BuildStateMachineHoistedLocalScopes(ILFunction function)
	{
		var builder = new BlobBuilder();
		foreach (var variable in function.Variables.Where(v => v.StateMachineField != null).OrderBy(v => MetadataTokens.GetRowNumber(v.StateMachineField.MetadataToken)))
		{
			builder.WriteUInt32(0);
			builder.WriteUInt32((uint)function.CodeSize);
		}
		return builder;
	}

	static byte[] ComputeSourceChecksum(string sourceText)
	{
		byte[] bytes = Encoding.UTF8.GetBytes(sourceText);
		using var hasher = SHA256.Create();
		return hasher.ComputeHash(bytes);
	}

	static BlobHandle WriteSourceToBlob(MetadataBuilder metadata, string sourceText)
	{
		var builder = new BlobBuilder();
		using (var memory = new MemoryStream())
		{
			var deflate = new DeflateStream(memory, CompressionLevel.Optimal, leaveOpen: true);
			byte[] bytes = Encoding.UTF8.GetBytes(sourceText);
			deflate.Write(bytes, 0, bytes.Length);
			deflate.Close();
			byte[] buffer = memory.ToArray();
			builder.WriteInt32(bytes.Length); // compressed
			builder.WriteBytes(buffer);
		}

		return metadata.GetOrAddBlob(builder);
	}

	static BlobHandle EncodeSequencePoints(MetadataBuilder metadata, int localSignatureRowId, List<SequencePoint> sequencePoints)
	{
		if (sequencePoints.Count == 0)
			return default;
		var writer = new BlobBuilder();
		// header:
		writer.WriteCompressedInteger(localSignatureRowId);

		int previousOffset = -1;
		int previousStartLine = -1;
		int previousStartColumn = -1;

		for (int i = 0; i < sequencePoints.Count; i++)
		{
			var sequencePoint = sequencePoints[i];
			// delta IL offset:
			if (i > 0)
				writer.WriteCompressedInteger(sequencePoint.Offset - previousOffset);
			else
				writer.WriteCompressedInteger(sequencePoint.Offset);
			previousOffset = sequencePoint.Offset;

			if (sequencePoint.IsHidden)
			{
				writer.WriteInt16(0);
				continue;
			}

			int lineDelta = sequencePoint.EndLine - sequencePoint.StartLine;
			int columnDelta = sequencePoint.EndColumn - sequencePoint.StartColumn;

			writer.WriteCompressedInteger(lineDelta);

			if (lineDelta == 0)
			{
				writer.WriteCompressedInteger(columnDelta);
			}
			else
			{
				writer.WriteCompressedSignedInteger(columnDelta);
			}

			if (previousStartLine < 0)
			{
				writer.WriteCompressedInteger(sequencePoint.StartLine);
				writer.WriteCompressedInteger(sequencePoint.StartColumn);
			}
			else
			{
				writer.WriteCompressedSignedInteger(sequencePoint.StartLine - previousStartLine);
				writer.WriteCompressedSignedInteger(sequencePoint.StartColumn - previousStartColumn);
			}

			previousStartLine = sequencePoint.StartLine;
			previousStartColumn = sequencePoint.StartColumn;
		}

		return metadata.GetOrAddBlob(writer);
	}

	static ImmutableArray<int> GetRowCounts(MetadataReader reader)
	{
		var builder = ImmutableArray.CreateBuilder<int>(MetadataTokens.TableCount);
		for (int i = 0; i < MetadataTokens.TableCount; i++)
		{
			builder.Add(reader.GetTableRowCount((TableIndex)i));
		}

		return builder.MoveToImmutable();
	}

	internal static string SyntaxTreeToString(SyntaxTree syntaxTree, DecompilerSettings settings)
	{
		StringWriter w = new StringWriter();
		TokenWriter tokenWriter = new TextWriterTokenWriter(w);
		tokenWriter = TokenWriter.WrapInWriterThatSetsLocationsInAST(tokenWriter);
		syntaxTree.AcceptVisitor(new CSharpOutputVisitor(tokenWriter, settings.CSharpFormattingOptions));
		return w.ToString();
	}

	sealed record PerFileResult(
		string Key,
		string SourceText,
		SyntaxTree SyntaxTree,
		Dictionary<ILFunction, List<SequencePoint>> SequencePoints,
		DebugInfoGenerator DebugInfoGen);
}
